---
language: php
services:
  - mysql
git:
  depth: 1
cache:
  directories:
    - $HOME/.composer
    - vendor

env:
  global:
    - PHP_CS_FIXER_IGNORE_ENV=1

matrix:
  include:
    - php: 7.1
      env: DB=mysql
    - php: 7.1
      env: DB=postgres
    - php: 7.2
      env: DB=mysql
    - php: 7.2
      env: DB=postgres
    - php: 7.3
      env: DB=mysql
    - php: 7.3
      env: DB=postgres

before_script:
  - composer install --dev
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE wtf;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE wtf;'; fi"
  - mkdir -p tests/coverage

script:
  - composer test:cs
  - composer test:unit

after_script:
  - travis_retry composer test:upload
